<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Game of life</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js" type="text/javascript"></script>
	<script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body>
	<div class="container">
  <section class="row">
  <h1>Game of life</h1>

  </section>

    <script src="js/index.js"></script>

  <section class="row">
    <button id="play">Play</button>
    <button id="stop">Stop</button>
    <button id="next">Next</button>

    <label>Width
    <input type="text" name="width" id="w" placeholder="width" value="20" />
    </label>

    <label>Height
    <input type="text" name="height" id="h" placeholder="height" value="20" />
    </label>

    <button id="setwh">Set</button>

  </section>

<section class="row">
  <div id="table">
  </div>

  <div id="buffer">
  </div>

</section>

</body>
</html>
